#!/bin/bash

source ./hw_vars

# usemem_mbind fails randomly. subsequent runs succeed. --have to fix that
USEMEM_MBIND=./usemem_mbind

# Allocate pages to scale with available free memory
PAGES=$((MemFree / nr_cpu / 20))

# run it for each cpu in system
for i in $(seq $nr_cpu)
do
$USEMEM_MBIND  $PAGES &
done
wait

