#!/bin/bash

source ./hw_vars

# prevent OOM: limit pagetable pages to half memory
(( ROTATE_BYTES > (mem << 8) )) && (( ROTATE_BYTES = (mem << 8) ))

$USEMEM -n $nr_cpu --readonly --random $((ROTATE_BYTES / nr_cpu))
