#!/bin/sh

. ./hw_vars

# prevent OOM: limit pagetable pages to half memory
[ "$ROTATE_BYTES" -gt $(( mem << 8 )) ] && ROTATE_BYTES=$(( mem << 8 ))

$USEMEM -t $nr_task --readonly --random $((ROTATE_BYTES / nr_task))
