#!/bin/sh

# flush memory with use-once page cache reads

# lru_lock coverage
# 1781926	____pagevec_lru_add
#  736056	shrink_inactive_list

. ./hw_vars

for i in `seq 1 $nr_task`
do
	create_sparse_file $SPARSE_FILE-$i $((ROTATE_BYTES / nr_task))
	$USEMEM -f $SPARSE_FILE-$i --readonly $((ROTATE_BYTES / nr_task)) &
done

wait

rm `seq -f $SPARSE_FILE-%g 1 $nr_task`
