#!/bin/bash

#
# Exercises functions in fremap.c of mm/
#
#
source ./hw_vars

USEMEM_REMAP=./usemem_remap

for i in $(seq $nr_cpu)
do
	create_sparse_file $SPARSE_FILE-$i $((mem / nr_cpu / 2))
	$USEMEM_REMAP  $SPARSE_FILE-$i $((mem / nr_cpu / 2)) &
done
wait

rm $SPARSE_FILE-*
