#!/bin/bash

# fill memory with clean shm/tmpfs pages

source ./hw_vars

create_sparse_file /dev/shm/XXX $shm_size

$USEMEM -f /dev/shm/XXX $((shm_size / 3)) --readonly --detach --sleep 100000 --pid-file $PIDFILE

rm /dev/shm/XXX
