#!/bin/sh

# step 1)  fill $mem with $nr_cpu files
# step 2)  truncate the files concurrently

. ./hw_vars

for i in `seq $nr_cpu`
do
	create_sparse_file $SPARSE_FILE-$i $((mem / nr_cpu))
	cp $SPARSE_FILE-$i /dev/null
done

t0=$(date +%s.%N)

for i in `seq $nr_cpu`
do
	rm $SPARSE_FILE-$i &
done

wait

t1=$(date +%s.%N)

echo $mem bytes truncated in $t1-$t0 seconds
