#!/bin/bash

# flush memory with use-once page cache reads

# lru_lock coverage
# 1781926	____pagevec_lru_add
#  736056	shrink_inactive_list

source ./hw_vars

for i in `seq 1 $nr_cpu`
do
	create_sparse_file $SPARSE_FILE-$i $((ROTATE_BYTES / nr_cpu))
	timeout -s INT ${runtime:-600} dd bs=4k if=$SPARSE_FILE-$i of=/dev/null > /tmp/dd-output-$i 2>&1 &
done

wait

cat /tmp/dd-output-*
rm  /tmp/dd-output-*
rm `seq -f $SPARSE_FILE-%g 1 $nr_cpu`
