#!/bin/bash

#
# Exercises code in mremap.c of mm/
#
# First creates a sparse file and then maps it to the VM of calling
#
# process. Then remaps it after scaling it by SCALE_FACTOR defined in usemem.
#

source ./hw_vars

for i in `seq $nr_cpu`
do
	create_sparse_file $SPARSE_FILE-$i $((ROTATE_BYTES / nr_cpu))
	$USEMEM -t $nr_cpu -f $SPARSE_FILE-$i -E --prealloc --readonly --random $((ROTATE_BYTES / nr_cpu)) &
done
wait

rm $SPARSE_FILE-*
